image: "node:latest"

cache:
    paths:
      - node_modules/  

stages:
    - lint
    - build

lint:
    stage: lint
    script:
        - npm install
        - npm run lint

build:
    stage: build
    script:
        - npm install
        - npm run build
    artifacts:
        paths:
            - .next
            - dist
        expire_in: 1 day